# required settings

service:
    name: "my-service"
    dns: endpoint.my.app
    port: 80

image:
    tag: latest
    repository: myrepo.acr.io

imagePullSecret: "my-pull-secret"

replicas: 1
port: 80

tls:
    secret: "tls-secret"

resources:
    requests:
        cpu: "250m"
        memory: "256Mi"
    limits:
        cpu: "250m"
        memory: "512Mi"
