# required settings

service:
    name: "my-service"
    dns: endpoint.my.app
    port: 80

image:
    tag: latest
    repository: myrepo.acr.io

replicas: 1
port: 80

resources:
    requests:
        cpu: "250m"
        memory: "256Mi"
    limits:
        cpu: "250m"
        memory: "512Mi"
