daemon:
    name: "my-service"

image:
    tag: latest
    repository: myrepo.acr.io

replicas: 1

resources:
    requests:
        cpu: "250m"
        memory: "256Mi"
    limits:
        cpu: "250m"
        memory: "512Mi"
