apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.daemon.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.daemon.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.daemon.name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        dapr.io/enabled: "true"
        dapr.io/app-id: {{ .Values.daemon.name }}
        dapr.io/app-port: "3000"
        dapr.io/config: "tracing"
      labels:
        app: {{ .Values.daemon.name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
      - name: {{ .Values.daemon.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        ports:
        envFrom:
          - configMapRef:
               name: {{ .Values.daemon.name }}-configmap
{{ if .Values.nodeName }}
      nodeSelector:
          kubernetes.io/hostname: {{ .Values.nodeName }}
{{ end }}
