apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: {{ .Values.name }}
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - {{ .Values.servicesCidrBlock }}
    serviceDomain: cluster.local  
  controlPlaneRef:
    apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureManagedControlPlane
    name: {{ .Values.name }}
  infrastructureRef:
    apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureManagedCluster
    name: {{ .Values.name }}
---
apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureManagedControlPlane
metadata:
  name: {{ .Values.name }}
spec:
  defaultPoolRef:
    name: {{ .Values.controlAgentPoolName }}
  location: {{ .Values.location }}
  resourceGroupName: {{ .Values.clusterResourceGroup }}
  nodeResourceGroupName: nodepool-{{ .Values.clusterResourceGroup }}
  sshPublicKey: ""
  subscriptionID: {{ .Values.subscriptionId }}
  version: {{ .Values.k8sVersion }} 
  networkPlugin: {{ .Values.networkPlugin }}
  networkPolicy: {{ .Values.networkPolicy }}
  virtualNetwork:
    name: {{ .Values.virtualNetwork.name }}
    cidrBlock: 10.0.0.0/8

---
apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureManagedCluster
metadata:
  name: {{ .Values.name }}
---
apiVersion: exp.cluster.x-k8s.io/v1alpha3
kind: MachinePool
metadata:
  name: {{ .Values.controlAgentPoolName }}
spec:
  clusterName: {{ .Values.name }}
  replicas: {{ .Values.controlAgentPoolNodes }}
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: {{ .Values.name }}
      infrastructureRef:
        apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AzureManagedMachinePool
        name: {{ .Values.controlAgentPoolName }}
      version: {{ .Values.k8sVersion }}
---
apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureManagedMachinePool
metadata:
  name: {{ .Values.controlAgentPoolName }}
spec:
  sku: {{ .Values.controlAgentPoolNodeSize }}
---
apiVersion: exp.cluster.x-k8s.io/v1alpha3
kind: MachinePool
metadata:
  name: {{ .Values.workerAgentPoolName }}
spec:
  clusterName: {{ .Values.name }}
  replicas: {{ .Values.workerAgentPoolNodes }}
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: {{ .Values.name }}
      infrastructureRef:
        apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AzureManagedMachinePool
        name: {{ .Values.workerAgentPoolName }}
      version: {{ .Values.k8sVersion }}
---
apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureManagedMachinePool
metadata:
  name: {{ .Values.workerAgentPoolName }}
spec:
  sku: {{ .Values.workerAgentPoolNodeSize }}